//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
    private JTextField heading;
    private JCheckBox robot_check;
    private JTextField username;
    private JTextField password;

    public MyPanel() {
        //construct components
        heading = new JTextField (5);
        robot_check = new JCheckBox ("newCheckBox");
        username = new JTextField (5);
        password = new JTextField (5);

        //set components properties
        robot_check.setToolTipText ("aa");

        //adjust size and set layout
        setPreferredSize (new Dimension (601, 384));
        setLayout (null);

        //add components
        add (heading);
        add (robot_check);
        add (username);
        add (password);

        //set component bounds (only needed by Absolute Positioning)
        heading.setBounds (180, 15, 235, 35);
        robot_check.setBounds (250, 245, 100, 25);
        username.setBounds (75, 90, 100, 25);
        password.setBounds (75, 150, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
